# 指定构建环境是Node.js，当前版本是稳定版
language: node_js
node_js: stable

# 设置钩子只检测blog-source分支的push变动
branches:
  only:
    - master

# 设置缓存文件
cache:
  directories:
    - node_modules

#安装git插件和搜索功能插件
install:
  - yarn

  # 设置git提交名，邮箱；替换真实token到_config.yml文件
# before_script:
  # - git config user.name "Michael728"
  # - git config user.email "649168982@qq.com"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
  # - sed -i "s/github_token/${GITHUB_TOKEN}/g" _config.yml || exit 1

# 执行清缓存，生成网页操作
script:
  - rm -rf dist
  - rm -rf out
  # - yarn lint
  - yarn build
  - yarn export
  - cd out
  - git init
  - git add .
  - git commit -m 'Travis build'
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/sailormillet/new-quiz-app.git" master:gh-pages
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - sailor_mi@163.com
  on_success: change
  on_failure: always